var LEDGER_APP = {
  name: 'Personal Trading Ledger',
  version: '0.1.0',
  defaultCurrency: 'USD',
};

var REQUIRED_SHEETS = [
  {
    name: 'Settings',
    headers: ['key', 'value', 'updated_at'],
    defaults: [
      ['base_currency', 'USD', ''],
      ['display_currency', 'USD', ''],
      ['usd_thb_rate_fallback', '34.5', ''],
      ['app_version', LEDGER_APP.version, ''],
    ],
  },
  {
    name: 'Portfolios',
    headers: [
      'portfolio_id',
      'name',
      'type',
      'market',
      'base_currency',
      'initial_capital',
      'commission_rate',
      'risk_mode',
      'default_risk_pct',
      'created_at',
      'updated_at',
      'archived',
    ],
  },
  {
    name: 'Positions',
    headers: [
      'position_id',
      'portfolio_id',
      'parent_position_id',
      'status',
      'symbol',
      'direction',
      'entry_date',
      'entry_price',
      'qty',
      'position_size',
      'stop_loss',
      'fee_entry',
      'exit_date',
      'exit_price',
      'exit_qty',
      'fee_exit',
      'realized_pnl',
      'note',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'ManualEntries',
    headers: [
      'entry_id',
      'portfolio_id',
      'date',
      'type',
      'amount',
      'balance_after',
      'currency',
      'note',
      'created_at',
    ],
  },
  {
    name: 'Holdings',
    headers: [
      'holding_id',
      'asset_type',
      'symbol',
      'name',
      'amount',
      'avg_cost',
      'cost_currency',
      'price_source',
      'custom_current_price',
      'note',
      'created_at',
      'updated_at',
      'archived',
    ],
  },
  {
    name: 'PriceCache',
    headers: ['symbol', 'source', 'price', 'currency', 'updated_at', 'is_stale'],
  },
  {
    name: 'DailySnapshots',
    headers: [
      'date',
      'total_portfolio_value_usd',
      'trading_value_usd',
      'holdings_value_usd',
      'cashflow_net_usd',
      'created_at',
    ],
  },
  {
    name: 'Watchlist',
    headers: ['symbol', 'source', 'created_at'],
  },
];
